Antodi99/product-feedback

src/App.tsx, src/components/EditFeedback.tsx
=> US009: add EditFeedback component

src/App.tsx, src/components/Card.tsx, src/components/Header.tsx, src/components/MainPage.tsx, src/components/ManageBar.tsx, src/components/UI/HeaderBox.tsx
=> US013: add MainPage component

src/App.tsx, src/components/EditFeedback.tsx, src/components/EditFeedbackPage.tsx, src/components/FeedbackPage.tsx, src/components/MainPage.tsx
=> US015: add EditFeedbackPage

src/App.tsx, src/components/AddFeedback.tsx, src/components/AddFeedbackPage.tsx, src/components/EditFeedback.tsx, src/components/FeedbackPage.tsx, src/components/ManageBar.tsx
=> US016: add AddFeedback page component

src/App.tsx, src/components/Header.tsx, src/components/RoadmapPage.tsx
=> US017: add RoadmapPage component(without mobile)

src/components/AddComment.tsx, src/components/FeedbackPage.tsx
=> US021: make AddComment work properly

src/components/AddComment.tsx, src/components/Comment.tsx
=> DE002 fix cursor on reply button

src/components/MainPage.tsx
=> DE001: fix bug 2 childrens with the same key

src/components/AddFeedback.tsx
=> US023: Make Select Category Menu work properly

src/components/MainPage.tsx, src/components/ManageBar.tsx, src/components/MenuDropdown.tsx
=> US018: Add logic to 'Sort By' filter(MainPage)

.eslintrc.js, src/components/Card.tsx, src/components/CattegoryButton.tsx, src/components/Header.tsx, src/components/MainPage.tsx
=> US022: Add logic to filter 'By Category'(MainPage)

src/components/Card.tsx
=> DE003: fixing votes button width

src/components/AddFeedbackPage.tsx, src/components/EditFeedbackPage.tsx, src/components/RoadmapPage.tsx
=> DE004: Make margin on the top the same at all pages

src/components/MainPage.tsx
=> DE005: Horizontal scroll on mobile & tablet screens

src/components/MainPage.tsx, src/components/NoFeedback.tsx, tailwind.config.js
=> US025: Show NotFound if there aren't feedback

README.md, src/App.tsx, src/components/LoginMenu.tsx, src/pages/LoginPage.tsx, src/services/auth.service.ts
=> US026: Add Login

package-lock.json, package.json, src/components/Comment.tsx, src/pages/FeedbackPage.tsx, src/pages/MainPage.tsx, src/services/feedback.service.ts, src/services/user.service.ts
=> US028: Fetch real feedback item

.eslintrc.js, src/App.tsx, src/pages/LoginPage.tsx, src/services/user.service.ts
=> US029: Redirect to /login page if user not logged

src/components/AddComment.tsx, src/pages/FeedbackPage.tsx, src/services/comments.service.ts, src/services/feedback.service.ts
=> US030: "Add comment" works

src/components/AddFeedback.tsx, src/services/feedback.service.ts
=> US032: Make AddFeedback form work

src/pages/edit-feedback-page/EditFeedbackPage.tsx
=> DE010: Go Back button navigates to the Main Page

src/components/Card.tsx, src/pages/edit-feedback-page/components/edit-feedback-form/EditFeedbackForm.tsx, src/pages/main/MainPage.tsx, src/pages/main/components/Card.tsx
=> DE007: Cancel button on Edit Feedback should navigate back to Feedback Page

src/components/Card.tsx, src/pages/main/MainPage.tsx, src/pages/main/components/Card.tsx
=> DE006: Votes button navigates to Feedback Page

src/pages/FeedbackPage.tsx
=> DE009: Add comment brakes Feedback Page

src/components/AddComment.tsx, src/components/Comment.tsx, tailwind.config.js
=> US035: Add validation to Add Comment on Feedback Page

src/App.tsx, src/components/FeedBackCard.tsx, src/pages/FeedbackPage.tsx, src/pages/RoadmapPage.tsx, src/pages/add-feedback-page/AddFeedbackPage.tsx, src/pages/edit-feedback-page/EditFeedbackPage.tsx, src/pages/main/components/Card.tsx, tailwind.config.js
=> US036: Roadmap Page works properly
